### PR TITLE
Pivot PyPI publishing to use trusted publishers

### PR DESCRIPTION
**Pull request by mtreinish**
This commit updates the wheel job CI configuration to leverage PyPI's trusted publisher mechanism. Moving forward the bot account we've been using will be deleted (as it will require 2fa) and the rustworkx github repository's wheels.yml workflow has been setup as a trusted publisher. This commit updates the job configuration per:

https://docs.pypi.org/trusted-publishers/using-a-publisher/

to autheticate the job directly against pypi for publishing the package files without needign any user credentials.

### CODE REVIEW

**Review by IvanIsCoding — APPROVED** [review]
LGTM but I think we should trigger it once before 0.14 to publish the current state to TestPyPI. Apparently it's not very hard:
```
repository-url: https://test.pypi.org/legacy/
```

**Comment by mtreinish** [comment]
It's a good thing you asked me to test this, I just setup my fork to push to `test.pypi.org` and it failed because the publish action only works on linux: https://github.com/mtreinish/retworkx/actions/runs/6538918751/job/17755862386#step:8:1

This is actually documented see:  https://github.com/pypa/gh-action-pypi-publish#non-goals I'll adjust the job to work with this and then retest.

**Comment by mtreinish** [comment]
Aside from the issue on non-linux runners, the trusted publisher upload works as expected to test pypyi: 

* https://github.com/mtreinish/retworkx/actions/runs/6538918751/job/17755862004#step:9:1
* https://test.pypi.org/project/rustworkx/#files

**Comment by IvanIsCoding** [comment]
> It's a good thing you asked me to test this, I just setup my fork to push to `test.pypi.org` and it failed because the publish action only works on linux: https://github.com/mtreinish/retworkx/actions/runs/6538918751/job/17755862386#step:8:1
> 
> This is actually documented see: https://github.com/pypa/gh-action-pypi-publish#non-goals I'll adjust the job to work with this and then retest.

An unfortunate surprise but I am glad we caught it. Upload artifacts seems like extra steps but I don’t think they’ll add Windows/mac support ever by the wording of their documentation

**Comment by mtreinish** [comment]
Ok, I've updated the job definition in: https://github.com/Qiskit/rustworkx/pull/1001/commits/781014a2e963103a327bffc5e6b1b794cd06be90 to use a a shared upload stage. Then I pushed another test to my fork branch on test pypi here: https://github.com/mtreinish/retworkx/commit/284e0551dfa6ca2a5dfe1cd8fd2a1ac15a3051da
and it is working as expecting:

https://github.com/mtreinish/retworkx/actions/runs/6552138251
https://test.pypi.org/project/rustworkx/0.14.1/#files (I bumped the version number to avoid file conflicts)

(the retworkx job failure is because I didn't bother configuring the trusted publisher pipeline for test pypi on retworkx)

**Review by IvanIsCoding — APPROVED** [review]
LGTM

**Pull request merged**
