### PR TITLE
Use rayon-cond for using multiple threads conditionally

### PR DESCRIPTION
**Pull request by jlapeyre**
This PR uses rayon-cond to conditionally use rayon threads (if the job is big enough to warrant the overhead).
Before this PR, code blocks are duplicated manually for serial and parallel code paths.

Implements issue #448

 - [x] Use rayon-cond for betweenness centrality
 - [x] Use rayon-cond in the remaining places where code was duplicated by hand

### CODE REVIEW

**Comment by jlapeyre** [comment]
I don't see an obvious way to use `CondIterator` here
https://github.com/Qiskit/retworkx/blob/747a4f6dad37e1e0495a7425e133dcc54b6cd6b7/src/shortest_path/floyd_warshall.rs#L132
since it doesn't seem to cover this functionality.

**Comment by jlapeyre** [comment]
Perhaps adding a threshold in some other places might be beneficial. Such as,
https://github.com/Qiskit/retworkx/blob/747a4f6dad37e1e0495a7425e133dcc54b6cd6b7/src/shortest_path/all_pairs_dijkstra.rs#L171-L211

**Comment by jlapeyre** [comment]
@mtreinish What do you think of merging this PR as it is? That is, it replaces previous uses of rayon with rayon-cond. But, it does not add any new uses of rayon/rayon-cond as suggested in https://github.com/Qiskit/retworkx/pull/450#issuecomment-919513145 . Those could be treated in a separate PR.

**Comment by mtreinish** [comment]
> @mtreinish What do you think of merging this PR as it is? That is, it replaces previous uses of rayon with rayon-cond. But, it does not add any new uses of rayon/rayon-cond as suggested in [#450 (comment)](https://github.com/Qiskit/retworkx/pull/450#issuecomment-919513145) . Those could be treated in a separate PR.

Yeah I think this is fine as scoping for merging this PR. We can look at adding more uses in a follow-up PR, I think that makes sense because there will be some benchmarking needed to find the threshold values for running in multiple threads by default.

**Review by mtreinish — COMMENTED** [review]
Did you want to update the betweenness centrality function to use rayon-cond too? It was moved to the retworkx-core crate as part of that split out: https://github.com/Qiskit/retworkx/blob/main/retworkx-core/src/centrality.rs#L106-L158

**Comment by jlapeyre** [comment]
> want to update the betweenness centrality function to use rayon-cond 

Oh yeah. I missed that some how. I'll do that.

**Pull request closed without merging**
